endpoint: wss://asset-hub-polkadot-rpc.n.dwellir.com
mock-signature-host: true
block: ${env.STATEMINT_BLOCK_NUMBER}
db: ./db/assethub.sqlite

wasm-override: ./wasm/frequency_runtime.wasm

import-storage:
  System:
    Account:
      - - - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000
