endpoint:
  - wss://0.rpc.frequency.xyz
  # - wss://1.rpc.frequency.xyz
mock-signature-host: true
block: ${env.FREQUENCY_BLOCK_NUMBER}
db: ./db/frequency.sqlite
# runtime-log-level: 5
# log-level: debug
# log-file: ./logs/frequency.log

# allow-unresolved-imports: true

wasm-override: ./wasm/frequency_runtime.wasm

import-storage:
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000
